# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
xcode_project: Example/ABMediaView.xcworkspace #3
xcode_scheme: ABMediaView-Example #4
xcode_sdk: iphonesimulator9.3

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/ABMediaView.xcworkspace -scheme ABMediaView-Example -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
